### ISSUE TITLE
[Android] Unmouting screen with FlatList causes java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by jankosecki** [reactwg/react-native-releases#430] opened 2024-08-14 17:37 UTC
### Old Version

0.74.5

### New Version

0.75-RC7

### Description

Hi team,

After upgrading to RN 0.75-RC7 android app crashes when a screen with `FlatList` component is dismounted.
We are using new architecture.

The reproduction contains `react-navigation` dependency to be able to navigate to and back from List screen but the stack trace seems to be purely related to cleaning up components of an unmounted view.

Reproducer repo `main` branch uses 0.74 which works fine and `rn-0.75` branch contains reproducible issue

### Steps to reproduce

1. Install the application with `yarn android`
2. Use "Go to List View" button to navigate to a screen which contains a FlatList component
3. Use "Back" button or "Back to Main" which uses `goBack` to returns to `Main` screen and unmounts current view

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M2
  Memory: 78.77 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.5.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/jkosecki/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/jkosecki/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.0-rc.7
    wanted: 0.75.0-rc.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
2024-08-14 18:29:27.015 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E    <ViewGroup tag=84 class=class com.facebook.react.views.view.ReactViewGroup>
2024-08-14 18:29:27.015 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E       <View idx=0 tag=56 class=class com.facebook.react.views.text.ReactTextView>
2024-08-14 18:29:27.016 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E       <View idx=1 tag=62 class=class com.facebook.react.views.text.ReactTextView>
2024-08-14 18:29:27.016 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E       <View idx=2 tag=68 class=class com.facebook.react.views.text.ReactTextView>
2024-08-14 18:29:27.016 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E       <View idx=3 tag=74 class=class com.facebook.react.views.text.ReactTextView>
2024-08-14 18:29:27.016 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E    </ViewGroup tag=84>
2024-08-14 18:29:27.016 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  Displaying Ancestors:
2024-08-14 18:29:27.016 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=86 class=class com.facebook.react.views.scroll.ReactScrollView>
2024-08-14 18:29:27.016 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=96 class=class com.facebook.react.views.view.ReactViewGroup>
2024-08-14 18:29:27.016 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=102 class=class com.swmansion.rnscreens.Screen>
2024-08-14 18:29:27.017 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=-1 class=class com.swmansion.rnscreens.ScreenStackFragment$ScreensCoordinatorLayout>
2024-08-14 18:29:27.017 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=28 class=class com.swmansion.rnscreens.ScreenStack>
2024-08-14 18:29:27.017 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=30 class=class com.th3rdwave.safeareacontext.SafeAreaProvider>
2024-08-14 18:29:27.017 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=11 class=class com.facebook.react.runtime.ReactSurfaceView>
2024-08-14 18:29:27.017 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=16908290 class=class androidx.appcompat.widget.ContentFrameLayout>
2024-08-14 18:29:27.017 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=2131230781 class=class androidx.appcompat.widget.FitWindowsLinearLayout>
2024-08-14 18:29:27.017 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=-1 class=class android.widget.FrameLayout>
2024-08-14 18:29:27.017 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=-1 class=class android.widget.LinearLayout>
2024-08-14 18:29:27.017 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=-1 class=class com.android.internal.policy.DecorView>
2024-08-14 18:29:27.017 21942-21942 unknown:Su...ingManager com.reactnativeupgradetester         E  <ViewParent tag=-1 class=class android.view.ViewRootImpl>
2024-08-14 18:29:27.021 21942-21942 unknown:Mo...Dispatcher com.reactnativeupgradetester         E  dispatchMountItems: caught exception, displaying mount state
                                                                                                    java.lang.IllegalStateException: Cannot remove child at index 4 from parent ViewGroup [84], only 5 children in parent. Warning: childCount may be incorrect!
                                                                                                    	at com.facebook.react.fabric.mounting.SurfaceMountingManager.removeViewAt(SurfaceMountingManager.java:582)
                                                                                                    	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:119)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:383)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:290)
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:123)
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1349)
                                                                                                    	at com.facebook.react.fabric.GuardedFrameCallback.doFrame(GuardedFrameCallback.kt:22)
                                                                                                    	at com.facebook.react.modules.core.ReactChoreographer$1.doFrame(ReactChoreographer.java:89)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:941)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8592)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
                                                                                                    Caused by: java.lang.IndexOutOfBoundsException
                                                                                                    	at android.view.ViewGroup.removeViewsInternal(ViewGroup.java:5707)
                                                                                                    	at android.view.ViewGroup.removeViewsInLayout(ViewGroup.java:5554)
                                                                                                    	at com.facebook.react.views.view.ReactViewGroup.removeViewsInLayout(ReactViewGroup.java:580)
                                                                                                    	at com.facebook.react.views.view.ReactViewGroup.removeViewWithSubviewClippingEnabled(ReactViewGroup.java:713)
                                                                                                    	at com.facebook.react.views.view.ReactClippingViewManager.removeViewAt(ReactClippingViewManager.java:77)
                                                                                                    	at com.facebook.react.views.view.ReactClippingViewManager.removeViewAt(ReactClippingViewManager.java:21)
                                                                                                    	at com.facebook.react.fabric.mounting.SurfaceMountingManager.removeViewAt(SurfaceMountingManager.java:557)
                                                                                                    	at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:119) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:383) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:290) 
                                                                                                    	at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:123) 
                                                                                                    	at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1349) 
                                                                                                    	at com.facebook.react.fabric.GuardedFrameCallback.doFrame(GuardedFrameCallback.kt:22) 
                                                                                                    	at com.facebook.react.modules.core.ReactChoreographer$1.doFrame(ReactChoreographer.java:89) 
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404) 
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415) 
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015) 
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:941) 
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8592) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
```

### Reproducer

https://github.com/jankosecki/react-native-upgrade-tester/tree/rn-0.75

**Comment by oblador** [comment] 2024-08-15 17:10
Likely duplicate of https://github.com/software-mansion/react-native-screens/issues/2282

**Comment by cortinico** [comment] 2024-08-15 17:27
@tboba is this something you folks are looking into?

**Comment by cortinico** [comment] 2024-08-15 17:27
Also @jankosecki can you try on 0.75.1 just to be on the latest stable (it's unlikely will fix it though)

**Comment by jankosecki** [comment] 2024-08-16 09:17
The issue persists in 0.75.1. However, as @oblador observed, this is most likely issue in `react-native-screens` and I can confirm that  `removeClippedSubviews={false}` prevents the crash.

I'm happy to close this issue if you agree that the fix is required only in `react-native-screens` library

**Comment by WoLewicki** [comment] 2024-08-19 10:20
Yeah, looks exactly like the issue we can spot in `react-native-screens`.

**Comment by cortinico** [comment] 2024-08-19 10:55
Ok so closing for now and we can reopen if we consider this a regression in react-native

**Closed by cortinico** 2024-08-19 10:55 UTC
Labels: Type: Upgrade Issue
