### ISSUE TITLE
[0.76] Fix cursor moving while typing quickly and autocorrection triggered in controlled single line TextInput on iOS (New Arch)

### ISSUE THREAD

**Issue by mhoran** [reactwg/react-native-releases#595] opened 2024-10-26 19:04 UTC
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/46970
https://github.com/facebook/react-native/commit/557e3447f520e40a1ec0ae344126b4f2836d2e83
and https://github.com/facebook/react-native/pull/47269.

### Description

A long standing bug with TextInput has been fixed in New Arch in the aforementioned PR. The bug manifested as many different issues, requiring various workarounds. As of 0.76, at least one of these workarounds no longer works in New Arch (https://github.com/facebook/react-native/issues/29572#issuecomment-699170797).

Related issues:
https://github.com/facebook/react-native/issues/29572
https://github.com/facebook/react-native/issues/42792
https://github.com/facebook/react-native/issues/27693
... and likely others.

**Comment by mhoran** [comment] 2024-10-27 03:44
Unfortunately after some testing it seems that the aforementioned issues are not fixed by this patch, though it is still likely worth pulling in.

**Comment by cipolleschi** [comment] 2024-10-28 10:14
@mhoran could you provide a repro with this ([template](https://github.com/react-native-community/reproducer-react-native)) to show that it is not fixed?

**Comment by cipolleschi** [comment] 2024-10-28 10:17
We might also need https://github.com/facebook/react-native/commit/557e3447f520e40a1ec0ae344126b4f2836d2e83

**Comment by blakef** [comment] 2024-10-28 14:12
Holding on this for 0.76.1, waiting for a reproducer.

**Comment by NickGerleman** [comment] 2024-10-29 00:28
Let me take a look at these, to see if something might have broke since the initial iteration of the change and what was merged. I'm also seeing this not fixed, which wasn't the case earlier.

Once that is settled, I do think we should pick the collection of changes. I was holding out until this week, since as of this Wednesday, the change will have been in major production apps for about a week.

**Comment by NickGerleman** [comment] 2024-10-29 01:18
@mhoran I think I tracked this down. Would you be able to try also applying the change in https://github.com/facebook/react-native/pull/47269 ?

The gist is that, the controlled component I used in testing accepted `value` as child instead of via `value` prop, and the case of accepting by `value` may have a separate bug causing inequality.

**Comment by mhoran** [comment] 2024-10-29 01:33
https://github.com/facebook/react-native/pull/47269 works for me! All the issues mentioned in https://github.com/reactwg/react-native-releases/issues/595#issuecomment-2441737925 are resolved with the three patches discussed:
https://github.com/facebook/react-native/pull/46970
https://github.com/facebook/react-native/commit/557e3447f520e40a1ec0ae344126b4f2836d2e83
and https://github.com/facebook/react-native/pull/47269.

Thanks for taking a look at this so quickly!

**Closed** 2024-11-12 18:59 UTC
Labels: Type: Pick Request
