### ISSUE TITLE
[0.75.0-rc.2]: regression on linking iOS dependencies with script phase (e.g. RN Firebase): 

### ISSUE THREAD

**Issue by imWildCat** [reactwg/react-native-releases#341] opened 2024-06-27 02:52 UTC
### Old Version

0.74.x

### New Version

0.75.0-rc2

### Description

Not sure whether rc1 has this problem as well. I found this problem while upgrading from 0.74.x to 0.75.x

Error:

```
➜  ios git:(main) pod install
RNFBAnalytics: Using default Firebase/Analytics with Ad Ids. May require App Tracking Transparency. Not allowed for Kids apps.
RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
Found 3 modules for target `AwesomeProject7`
link_native_modules! {:ios_packages=>[{:configurations=>[], :name=>"@react-native-firebase/analytics", :path=>"../node_modules/@react-native-firebase/analytics", :podspec_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/node_modules/@react-native-firebase/analytics/RNFBAnalytics.podspec", :script_phases=>[]}, {:configurations=>[], :name=>"@react-native-firebase/app", :path=>"../node_modules/@react-native-firebase/app", :podspec_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/node_modules/@react-native-firebase/app/RNFBApp.podspec", :script_phases=>[{"name"=>"[RNFB] Core Configuration", "path"=>"./ios_config.sh", "execution_position"=>"after_compile", "input_files"=>["$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"]}]}, {:configurations=>[], :name=>"react-native-svg", :path=>"../node_modules/react-native-svg", :podspec_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/node_modules/react-native-svg/RNSVG.podspec", :script_phases=>[]}], :ios_project_root_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/ios", :react_native_path=>"../node_modules/react-native"}
RNFBAnalytics: Using default Firebase/Analytics with Ad Ids. May require App Tracking Transparency. Not allowed for Kids apps.
RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration

[!] Invalid `Podfile` file: No such file or directory @ rb_sysopen - /Volumes/QuickMac/temp/202406/AwesomeProject7/ios/ios_config.sh.

 #  from /Volumes/QuickMac/temp/202406/AwesomeProject7/ios/Podfile:18
 #  -------------------------------------------
 #  target 'AwesomeProject7' do
 >    config = use_native_modules!
 #  
```

I thought it was something like pnpm workspace but it is not.

### Steps to reproduce

1. `git clone https://github.com/imWildCat-archived/react-native-075-rc2-regression-ios-linking-script-phase`
2. `cd react-native-075-rc2-regression-ios-linking-script-phase`
3. `yarn install`
4. `cd ios`
5. `pod install`

### Affected Platforms

Runtime - iOS, Build - MacOS

### Output of `npx react-native info`

```text
➜  AwesomeProject7 git:(main) yarn react-native info                                              
info Fetching system and libraries information...
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Max
  Memory: 218.66 MB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.14.0
    path: /private/var/folders/j8/0c4r57j93w1fgrwhr31z6z_c0000gn/T/xfs-94018d4a/node
  Yarn:
    version: 3.6.4
    path: /private/var/folders/j8/0c4r57j93w1fgrwhr31z6z_c0000gn/T/xfs-94018d4a/yarn
  npm:
    version: 10.7.0
    path: /opt/homebrew/opt/node@20/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/wildcat/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    Android NDK: 26.1.10909125
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.3.2
    path: /Users/wildcat/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 19.0.0-rc-fb9a90fa48-20240614
    wanted: 19.0.0-rc-fb9a90fa48-20240614
  react-native:
    installed: 0.75.0-rc.2
    wanted: 0.75.0-rc.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
```
```


### Stacktrace or Logs

```text
➜  ios git:(main) pod install
RNFBAnalytics: Using default Firebase/Analytics with Ad Ids. May require App Tracking Transparency. Not allowed for Kids apps.
RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
Found 3 modules for target `AwesomeProject7`
link_native_modules! {:ios_packages=>[{:configurations=>[], :name=>"@react-native-firebase/analytics", :path=>"../node_modules/@react-native-firebase/analytics", :podspec_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/node_modules/@react-native-firebase/analytics/RNFBAnalytics.podspec", :script_phases=>[]}, {:configurations=>[], :name=>"@react-native-firebase/app", :path=>"../node_modules/@react-native-firebase/app", :podspec_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/node_modules/@react-native-firebase/app/RNFBApp.podspec", :script_phases=>[{"name"=>"[RNFB] Core Configuration", "path"=>"./ios_config.sh", "execution_position"=>"after_compile", "input_files"=>["$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"]}]}, {:configurations=>[], :name=>"react-native-svg", :path=>"../node_modules/react-native-svg", :podspec_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/node_modules/react-native-svg/RNSVG.podspec", :script_phases=>[]}], :ios_project_root_path=>"/Volumes/QuickMac/temp/202406/AwesomeProject7/ios", :react_native_path=>"../node_modules/react-native"}
RNFBAnalytics: Using default Firebase/Analytics with Ad Ids. May require App Tracking Transparency. Not allowed for Kids apps.
RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration

[!] Invalid `Podfile` file: No such file or directory @ rb_sysopen - /Volumes/QuickMac/temp/202406/AwesomeProject7/ios/ios_config.sh.

 #  from /Volumes/QuickMac/temp/202406/AwesomeProject7/ios/Podfile:18
 #  -------------------------------------------
 #  target 'AwesomeProject7' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```
```


### Reproducer

https://github.com/imWildCat-archived/react-native-075-rc2-regression-ios-linking-script-phase

### Screenshots and Videos

_No response_

**Comment by imWildCat** [comment] 2024-06-27 02:54
might be related to https://github.com/reactwg/react-native-releases/issues/336

**Comment by cortinico** [comment] 2024-06-27 03:42
Thanks for the repro @imWildCat 👍 That's something for @cipolleschi to investigate

**Comment by imWildCat** [comment] 2024-06-27 03:44
Thanks for the quick reply, @cortinico ! ❤️

**Comment by cipolleschi** [comment] 2024-06-27 11:05
@imWildCat have you tried applying the fixes suggested by https://github.com/facebook/react-native/pull/45165 in your repro?
Does it fixes it?

**Comment by imWildCat** [comment] 2024-06-27 12:13
No I haven’t 

is there any quick way to apply that diff?

**Comment by imWildCat** [comment] 2024-06-27 15:36
@cipolleschi I checked the git history of the autolinking.rb file but haven't found any bad commit.

Created this PR https://github.com/facebook/react-native/pull/45208/

There might be better way

**Comment by imWildCat** [comment] 2024-06-27 15:36
the fix is demonstrated at <https://github.com/imWildCat-archived/react-native-075-rc2-regression-ios-linking-script-phase/commit/471521351361f34059b50833537a8ab3cc06633a>

**Comment by cipolleschi** [comment] 2024-06-28 10:06
closed by e320ab47cf855f2e5de74ea448ec292cf0bbb29a

**Closed by cipolleschi** 2024-06-28 10:06 UTC
Labels: Type: Upgrade Issue

**Comment by mikehardy** [comment] 2024-06-28 16:24
Oh you beat me to it!! Didn't see this, logged #345 
Will close mine. Awesome @imWildCat thank you!

**Comment by cortinico** [comment] 2024-07-01 10:30
Pick request for the fix is here (for reference): 
- https://github.com/reactwg/react-native-releases/issues/342

**Comment by matinzd** [comment] 2024-08-20 14:01
I guess one of these fixes has caused `pod install` to fail even in 0.75.2 with monorepos. Is anyone else having this issue?

**Comment by cipolleschi** [comment] 2024-08-22 12:39
@matinzd I just tried spinning up a new project with 0.75.2 and everything works for me.

That's the script I run
```
npx react-native@latest init TestPodInstall --version next --skip-install
cd TestPodInstall
yarn install
cd ios
bundle install
cd ..
USE_FRAMEWORKS=static RCT_NEW_ARCH_ENABLED=1 bundle exec pod update --project-directory=ios
```

If you are in a monorepo, there might be something in your specific monorepo setup.

If the problem is:

```
[!] Invalid `Podfile` file: No such file or directory @ rb_sysopen - /Users/cipolleschi/Tests/node_modules/@react-native-firebase/app/ios_config.sh.
``` 
the problem is in Firebase, that is hardcoding the path to `@react-native-firebase/app/ios_config.sh` [here](https://github.com/invertase/react-native-firebase/blob/d28b8946e28bc4a934a3827d1c7103d51682987c/packages/app/react-native.config.js#L11). They should probably do a `resolve` to look for the right file path.

**Comment by matinzd** [comment] 2024-08-22 14:01
But it's weird that this was working before 75. That needs to be fixed but I am wondering if there has been some breaking changes with introducing the path.

**Comment by cipolleschi** [comment] 2024-08-22 16:27
uhm, good point. I think it might related to the changes we made with autolinking, then.

@blakef can you chime in here?

**Comment by matinzd** [comment] 2024-08-22 18:37
Now that there have been changes in auto linking do you think this can be related as well?

https://github.com/software-mansion/react-native-screens/issues/2306

**Comment by blakef** [comment] 2024-08-23 15:26
So this is because before 0.75 we used to use an absolute path instead of a relative path (introduced in #45208).  So you get paths looking like this:

![CleanShot 2024-08-23 at 16 17 49@2x](https://github.com/user-attachments/assets/6e70ec8a-0ad2-4af8-9727-9097e4afbde2)

You can see how that quickly falls apart when using `--project-directory`.  I'll put up a fix passing the `root` with the package and using that instead of `path`.

**Comment by blakef** [comment] 2024-08-23 15:49
> Now that there have been changes in auto linking do you think this can be related as well?
> 
> [software-mansion/react-native-screens#2306](https://github.com/software-mansion/react-native-screens/issues/2306)

I don't think it's related.  This path just affects package scripts AFAIK.  For what it's work I added `react-native-screens` to a basic project on `0.75.2` and it seemed to build fine on iOS.

**Comment by matinzd** [comment] 2024-08-24 19:00
Thanks for fixing it the auto-linking issue! 🌸 

Have you tried rnscreens with new arch turned on?

**Comment by xxsnakerxx** [comment] 2024-08-27 09:21
```diff
- phase["script"] = File.read(File.expand_path(phase["path"], package[:path]))
+ phase["script"] = File.read(File.expand_path(File.join(package[:path], phase["path"]), ios_project_root))
```
